### ISSUE TITLE
lack of file latplan.py

### ISSUE THREAD

**Issue by ZHMA1996** [guicho271828/latplan#1]
An error occured when i ran the file train_all.sh. The command line implied no moudle named 'latplan' when running strips.py at line 6. I would be delighted if you can offer me the complete file.Thanks.

**Comment by guicho271828** [comment]
https://github.com/guicho271828/latplan/blob/master/install.sh
```
cat >> ~/.profile <<EOF
# This is added by latplan install.sh script.
export PYTHONPATH="$PWD:\$PYTHONPATH"
EOF
```
the parent directory should be in the path and the repository itself becomes a module

**Comment by guicho271828** [comment]
I know there is a better way, but don't want to move everything to lose the commit history (I was a python novice when I started the project)

**Comment by ZHMA1996** [comment]
The problem has been solved.
Thanks a lot!

**Comment by guicho271828** [comment]
> I know there is a better way, but don't want to move everything to lose the commit history (I was a python novice when I started the project)

Now I learned about https://github.com/newren/git-filter-repo and am more experienced with python packaging with setuptools and conda, I am planning an update that moves the source files by rewriting the commit history, and making latplan pip loadable.
