### ISSUE TITLE
How to use the Cube-Space AE (with trained weights) to encode images

### ISSUE THREAD

**Issue by wn4github** [guicho271828/latplan#11]
I'm trying to use the Cube-Space AE with the trained weights to encode some MNIST 8-puzzle images, could you please explain  the requirement of these images and procedures (or code) for this task?

The environment:
- I am using the 4.1.3 version of source code; run `./setup-dataset.py`
- `./samples` now contains a bunch of directories
```
...
puzzle_mnist_3_3_5000_None_100_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_fixedactions
puzzle_mnist_3_3_5000_None_200_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_fixedactions
puzzle_mnist_3_3_5000_None_300_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_fixedactions
puzzle_mnist_3_3_5000_None_50_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_fixedactions
puzzle_mnist_3_3_5000_None_None_0.0_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_nodirect
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetBoolAddEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetBoolMinMaxEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetBoolSmoothMinMaxEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetLogitAddEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_planning
puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetNoSucNormalizedLogitAddEffectTransitionAE_arch
puzzle_mnist_3_3_5000_None_None_None_False_VanillaTransitionAE_vanilla
...
```
- I uncompressed the trained weight archive to a separate directory and I saw the following subdirectory `puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_planning` in `./weights/samples/`. 
`let P := puzzle_mnist_3_3_5000_None_None_None_False_ConcreteDetNormalizedLogitAddEffectTransitionAE_planning`
- I notice the single file `grid_search.log` in `./samples/P/`, but this file is not in `./weights/samples/P/`. I guess `grid_search.log` is used to record the result of grid-searching hyper parameters, and the floating point number of each line is the performance for that grid.
- 
My questions are
1. If I am trying to use the weights for MNIST 8-puzzle, do I just copy every file in `./weights/samples/P/` to `./samples/P/`?
2. Say I have an image of a MNIST 8-puzzle state `[1 _ 2; 3 4 5; 6 7 8]` and I want to use Cube-Space AE to encode the image into bit-vector representation, and maybe decode the vector back to image representation, where do I put the image file and what are the image file requirement (weight/height, format)?
3. Are there any functions that directly encode/decode the image/vector? If not, which part of the code should I look into?

**Comment by guicho271828** [comment]
> If I am trying to use the weights for MNIST 8-puzzle, do I just copy every file in ./weights/samples/P/ to ./samples/P/?

That is correct.

> Say I have an image of a MNIST 8-puzzle state [1 _ 2; 3 4 5; 6 7 8] and I want to use Cube-Space AE to encode the image into bit-vector representation, and maybe decode the vector back to image representation, where do I put the image file and what are the image file requirement (weight/height, format)?

MNIST 8-puzzle image is a monochrome, 42x42 image. While I still work on (the fork of) this code base, I no longer remember the image size because I abstract everything in my code base and I have a bunch of datasets, not just MNIST-8puzzle. You can confirm the image size by inserting some `print` here. https://github.com/guicho271828/latplan/blob/v4.1.3/strips.py#L200

There is no interface for directly reading a file stored in your disk. You need to write new code for it.
The `AE` class, which is inherited by all AE classes in `model.py`, has `encode` and `decode` method which takes a numpy array.
It should be a batched input, so dont forget having adding the dimension even for a single image, e.g. [1, h, w, 1]

**Comment by guicho271828** [comment]
closing due to the latest release v5.0.0 .
