### ISSUE TITLE
grovelling +magic-version+ from MAGIC_VERSION in magic.h header file failed!

### ISSUE THREAD

**Issue by rakhmanu** [guicho271828/latplan#14]
Dear Mr. @guicho271828,

This issue is similar to the previous issue #13, however installing header file by sudo apt-get install libmagic-dev does not solve it.
The magic.h file exists, but i do not know why it fails. Please guide me to tackle with this problem. 
 
To load "magicffi":
  Load 1 ASDF system:
    magicffi
; Loading "magicffi"
[1/3] System 'magicffi' found. Loading the system..Aborted during step [1/3].
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {1001549123}>:
  grovelling +magic-version+ from MAGIC_VERSION in magic.h header file failed!

Thank you very much,
Sincerely, Ulzhalgas Rakhman

**Comment by guicho271828** [comment]
Hi could you tell me the version of libmagic you have installed?

**Comment by rakhmanu** [comment]
> Hi could you tell me the version of libmagic you have installed?
Hi, yes

file-5.38
magic file from /etc/magic:/usr/share/misc/magic

Thank you very much,
Sincerely, Ulzhalgas Rakhman

**Comment by guicho271828** [comment]
hmm, seeing this line, there has been no change since the last 9 years, so it is not that it is breaking.
https://github.com/file/file/blame/FILE5_38/src/magic.h.in#L116
I wonder if `/etc/magic` actually contains the header file `magic.h` (that is the whole point of installing the header file)
and it is included in the CPATH.

**Comment by rakhmanu** [comment]
@guicho271828 , thank you very much for your.
That solved my problem. Sorry i forgot to close the issue.

Sincerely, Ulzhalgas Rakhman

**Comment by vindarel** [comment]
Hi there, could you explain how you solved the issue? I am having this while trying to install magicffi with Quicklisp (note: there are no issue tracker in magicffi).

My system dependencies are:

* libmagic-dev: 1:5.32-2ubuntu0.4
* libc6-dev: 2.27-3ubuntu1.4
* gcc: 4:7.4.0-1ubuntu2.3

and:

```
$ ls -lh /etc/magic*                             
-rw-r--r-- 1 root root 111 Feb 13  2018 /etc/magic
-rw-r--r-- 1 root root 111 Feb 13  2018 /etc/magic.mime
```

No /etc/magic directory. I can't see a magic.h file.  There is one in `/usr/include/magic.h`, `/usr/include/linux/magic.h` and `/usr/include/ImageMagick-6/magick/magic.h` (and `/gnu/store/gfapkk5c6hvl1d94m4sqnhn7f9l5gqyh-linux-libre-headers-5.4.20/include/linux/magic.h`, but it shouldn't interfere with my installation).

```
$ echo $CPATH

```

So

> Have magic.h in the C compiler's include path, aka $CPATH.

how do you do that? (anything else to do from a Common Lisp REPL?)

thank you

**Comment by guicho271828** [comment]
it seems the installation point varies among systems ... and I am not keen on searching the file from inside common lisp, because it could be brittle. Asking the users to modify and export CPATH would be a surefire way. Anotehr way is to include `magic.h` in magicffi but that has a danger of having an obsolete file that is different from original `libmagic`.

**Comment by vindarel** [comment]
> Asking the users to modify and export CPATH would be a surefire way.

I… would welcome an example.

> searching the file from inside common lisp, because it could be brittle

I undesrtand. Maybe searching in a few locations? For example, in cl-readline, we search several files:

```lisp
(define-foreign-library readline
  ;; On OSX we first search readline, installed by brew install readline
  ;; because native system version of readline is a symlink to libedit.
  ;; Some people on the internet advice to "fix" it by running:
  ;; brew link --force readline
  ;; but it is a bad idea, because this command may break some system utilities,
  ;; depending on libedit's internals.
  (:darwin (:or "/usr/local/opt/readline/lib/libreadline.dylib"
                "/opt/homebrew/opt/readline/lib/libreadline.dylib"
                "libreadline.dylib"))
  (:unix   (:or "libreadline.so.6.3"
                "libreadline.so.6"
                "libreadline.so.7"
                "libreadline.so.8"
                "libreadline.so"))
  (t       (:default "libreadline")))
```

thanks

**Comment by vindarel** [comment]
editing grovel.lisp to the location of my magic.h did the trick:

```lisp
(include "/etc/[…]/magic.h")
```

Best,

**Comment by guicho271828** [comment]
@vindarel yes, d-f-l has that feature which searches for several possible candidates, but the gloveller doesn't have it.

**Comment by guicho271828** [comment]
The important difference being whether it's searching for a shared object or a header file

**Comment by guicho271828** [comment]
> I… would welcome an example.

Just `export CPATH=/usr/include/linux sbcl`

**Comment by vindarel** [comment]
Thanks for that and the explanation <3
