### ISSUE TITLE
Compatibility issue + error

### ISSUE THREAD

**Issue by aymeric75** [guicho271828/latplan#17]
Hello,

Your code is supposed to run with **tensorflow 1.15** and **python 3.8**, nevertheless tensorflow 1.15 **is not** compatible with 3.8, see screenshot below.

![image](https://user-images.githubusercontent.com/12927600/155145493-954b330a-79e1-41e0-ad3e-8ad8934acf2a.png)

Also, when running your code with a different version of tensorflow (2.4), for instance with this command line:
`
latplan dump puzzle mnist 3 3 55 AE`

it creates an error:
`
TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, 48, 48) dtype=float32 (created by layer 'tf.reshape_2')> with type KerasTensor`

**Comment by guicho271828** [comment]
As documented, you need a Tensorflow port from NVIDIA. It supports newer hardware and python 3.8.
