### ISSUE TITLE
No definition of plot_transitions in network.py

### ISSUE THREAD

**Issue by aymeric75** [guicho271828/latplan#18]
In latplan\latplan\network.py there is this piece of code:

```
              on_epoch_end = lambda epoch,logs: \
                    self.plot_transitions(
                        plot_val_data,
                        self.path+"/",
                        epoch=epoch),
```

But no definition of **plot_transitions** function in _network.py_

So for instance, when I run 

>latplan learn puzzle mnist 3 3 40000 StateAE

I get this error:

```
  File latplan/network.py line 450 function <lambda> : self.plot_transitions(
                   epoch = 50
                    logs = {'t_loss': 237913.65086805556, 'v_loss': 236870.45}
           plot_val_data = '<numpy.ndarray float32  (1, 2, 48, 48, 1)>'
                    self = <latplan.model.StateAE object at 0x14b2840da4c0>

                     AttributeError: 'StateAE' object has no attribute 'plot_transitions'

```

Best regards

**Comment by guicho271828** [comment]
Yeah, it is an older model, please consider cubespaceae etc.

**Comment by aymeric75** [comment]
Hello,

Thanks, now I do 
`latplan learn puzzle mnist 3 3 40000 CubeSpaceAE_AMA4Plus` instead

But, it's strange because once in the "train" function  (in _latplan\network.py_) then nothing happens. This function does not call any Keras training function (e.g _fit_)

The only training function that I see is in _plot_transitions_ function (also in _network.py_) but this function does not seems to be called with 'latplan learn..'
