### ISSUE TITLE
Could you please add more information for ZSAE?

### ISSUE THREAD

**Issue by rakhmanu** [guicho271828/latplan#8]
Hi,

I am very interested in LatPlan and i used SAE+AMA1(old version) with my own dataset, however when i increase width, height to 5 in puzzle function, training process was killed. (I guess it was caused by out-of-memory,  not sure). 
Ubuntu 16.04
CUDA 10.0 
GPU NVIDIA TU102 -> 10989 MiB
For this reason, i wanted to use ZSAE, because according to your paper, ZSAE is SAE with additional regularization. It was said that it reduces the memory usage of the network by pruning some unused neurons. Then in your code, there are additional parameters such as zerosuppress, zerosuppress_delay for ZSAE. Could you please provide more information what are the meanings of those parameters? 

Thank you very much,
Sincerely, Ulzhalgas Rakhman

**Comment by guicho271828** [comment]
they are introduced recently, see IJCAI20 paper where I mention those delays.

**Comment by guicho271828** [comment]
pruning does not help the memory usage during the training. It is something you could do after you finish the training

**Comment by guicho271828** [comment]
closing due to the latest release v5.0.0 . For the theoretical justification, see the journal paper section 4. https://arxiv.org/abs/2107.00110
